### ISSUE TITLE
Fix AppEngine Servlet API version to be 3.1.0

### ISSUE THREAD

**Issue by alexander-yevsyukov** [spine-examples/todo-list#107]
The code currently uses Servlet API version `4.0.0` (see the constant `        appEngineServletApi` in `version.gradle`). AppEngine version we use supports only `3.1.0`.

The problem is features of v4.0 are used in the code. For example:

`io.spine.examples.todolist.server.CrossOriginResourceSharingFilter` extends `javax.servlet.http.HttpFilter` which is available only since Sevlets API v4.0.

**Comment by dmitrykuzmin** [comment]
Done with #130.
